### ISSUE TITLE
Output of TICs as 0 when using `tess_stars2px

### ISSUE THREAD

**Issue by Atousa-Kalantari** [tessgi/tess-point#17]
Hi,

I am using the following command:

python -m tess_stars2px -c 84.291188 -80.469119

However, the output of all TICs is coming out as 0. Is there a way to input RA and Dec values and get the corresponding TIC IDs?
Thank you for your help!

**Comment by Nschanche** [comment]
Hi @Atousa-Kalantari, Tess-point is designed to be a coordinate-to-pixel and vice versa tool, so it intentionally does not try to resolve the coordinates. Resolving coordinates is complicated for reasons including proper motion, duplicate sources, or conflicting sources. However, the GI office does supply other codes that are designed to help you with name resolving. 

One easy command-line option is [ticinfo](https://github.com/tessgi/ticinfo), which you just need to supply the coordinates for:
`toco 84.291188 -80.469119`

Another option to use lightkurve to resolve a provided target:
`lk.search_lightcurve("84.291188 -80.469119").target_name.data`

The new lksearch package will do a similar search:
`lksearch.TESSSearch("84.291188, -80.469119", pipeline='SPOC').target_name`

Both of the lk options provide a list of TIC IDs, one for each data entry.

Both lightkurve.search() and lksearch.TESSSearch() are wrappers for the underlying [MAST query](https://astroquery.readthedocs.io/en/latest/mast/mast_obsquery.html#observation-criteria-queries), so you may prefer to access this directly to conduct a cone search surrounding your coordinates. 

I'll close this issue now, but if you have any issues please get back in touch.
