### ISSUE TITLE
mismatch between NASA NSPIRES and TESS-point

### ISSUE THREAD

**Issue by awmann** [tessgi/tess-point#20]
D.10 TESS GENERAL INVESTIGATOR – Cycle 8 on NSPIRES gives the following parameters for Cycle 8:

![Screenshot 2024-12-12 at 1 38 01 PM](https://github.com/user-attachments/assets/6d56b8b9-df23-4947-96d1-e27144285a93)

The corresponding parameters in tess-point for RA are:
                    32.58859, 51.07802, 70.28258, \
                    90.12233, 188.30483,215.46263, \
                    213.02554,269.79802,238.67968, \
                    255.91506, 273.85979], dtype=float)
and for Dec:
                    -46.02539, -38.03354, -32.52732, \
                    -30.56408, -3.58419, -14.11836, \
                    -13.29335, -23.43662, 35.45995, \
                    31.56967, 30.64000], dtype=float)
(that's copy/pasted from tess_stars2px.py)
Unless I've missed something (certainly possible), these don't match. The resulting plots also don't match the ones from NSPIRES.

Which is correct?

**Comment by christinahedges** [comment]
Hi @awmann thanks for bringing this up, you're correct that the update for the Cycle 8 pointings doesn't match the truth at all. I'll figure out what went wrong here, but for now I've patched this and released an updated version. Thanks for opening this issue!!

I'm going to close this for now, but if you notice anything else please don't hesitate to open an issue.
